version: '3.5'

services:
 db:
   image: postgres:14
   environment:
     - POSTGRES_PASSWORD=vJ9QntZ9
     - POSTGRES_DB=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
     - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
   volumes:
     - ./database:/var/lib/postgresql/data
   ports:
     - "5432:5432"
   expose:
     - 5432
   restart: always
   deploy:
     restart_policy:
       condition: on-failure
       max_attempts: 3